#!/usr/bin/env python3
"This script draws the rectangles described by http://open.qa/docs/#_areas"

import re
import json
import sys

from PIL import Image, ImageDraw

COLORS = {'match': 'green', 'exclude': 'red', 'ocr': 'orange'}
THICKNESS = 2


def show_needle(pathname: str):
    "Main function"
    needle = re.sub(r"\.?(png|json)?$", "", pathname)

    try:
        image = Image.open(f"{needle}.png").convert('RGBA')
    except OSError as err:
        print(f"ERROR: {err}", file=sys.stderr)
        sys.exit(1)

    draw = ImageDraw.Draw(image)

    try:
        with open(f"{needle}.json", encoding="utf-8") as file:
            data = json.load(file)
    except OSError as err:
        print(f"ERROR: {err}", file=sys.stderr)
        sys.exit(1)

    # Draw rectangles
    for item in data['area']:
        for i in range(THICKNESS):
            draw.rectangle(
                [
                    item['xpos'] + i,
                    item['ypos'] + i,
                    item['xpos'] - i + item['width'],
                    item['ypos'] - i + item['height']
                ],
                outline=COLORS[item['type']])

    image.show()


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} NEEDLE[.json|png]", file=sys.stderr)
        sys.exit(1)

    try:
        show_needle(sys.argv[1])
    except KeyboardInterrupt:
        sys.exit(1)
